# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger: none

pr:
- main

schedules:
  - cron: '0 6 * * *'
    displayName: 'Morning run at 6 AM'
    branches:
      include: 
      - main
    always: true

pool:
  vmImage: windows-latest

parameters:
    - name: browser
      displayName : Browser for UI tests execution
      default: chrome
      type: string
      values:
          - chrome
          - firefox
          - edge
variables:
  buildConfiguration: 'Release'
  frameworkVersion: 'net6.0-windows'

steps:
      - task: DotNetCoreCLI@2
        displayName: 'Building project'
        inputs:
          command: 'build'
          arguments: '--configuration $(buildConfiguration)'

      - task: DotNetCoreCLI@2
        displayName: 'API tests run'
        continueOnError: true
        inputs:
            command: test
            projects: '**/*Tests/*.csproj'
            arguments: '--configuration $(buildConfiguration) --filter TestCategory=API'
      - task: DotNetCoreCLI@2
        displayName: 'UI tests run'
        condition: succeededOrFailed()
        inputs:
            command: test
            projects: '**/*Tests/*.csproj'
            arguments: '--configuration $(buildConfiguration) --filter TestCategory=UI -- TestRunParameters.Parameter(name="\""browser"\"", value="\""${{ parameters.browser }}"\"")'
      - task: PublishPipelineArtifact@1
        displayName: 'Publish screenshots'
        inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/TestAutomation.Tests/bin/$(buildConfiguration)/$(frameworkVersion)/Screenshots'
              publishLocation: 'pipeline'
              artifactName: Screenshots
        condition: failed()

